name: Auto Commit

on:
  schedule:
    - cron: "0 16 * * *"   # daily (UTC time)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make changes
        run: |
          echo "$(date)" >> activity.txt

      - name: Commit changes
        run: |
          git config --global user.name "anujrwt08"
          git config --global user.email "anujrwt08@users.noreply.github.com"
          git add .
          git commit -m "Auto commit $(date)" || echo "No changes"
          git push
