name: Auto Commit

on:
  schedule:
    - cron: "0 16 * * *"   # Runs daily (UTC)
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update file
        run: |
          echo "Auto commit on $(date)" >> activity.txt

      - name: Commit and push
        run: |
          git config --global user.name "anujrwt08"
          git config --global user.email "anujrwt08@users.noreply.github.com"
          git add .
          git commit -m "Auto commit $(date)" || echo "No changes"
          git push
